[project]
name = "gpt-robot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.23.0",
    "environs>=14.5.0",
    "httpx>=0.28.1",
    "redis>=7.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.9",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["RUF001", "RUF002", "D100", "D101", "D102", "D104", "D107"]
exclude = ["tests"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
